---
title: "Weight of Fish"
author: "Taylor Stohl"
date: "Summer 2021"
output: 
  html_document:
    number_sections: true
    toc: true
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
read.csv 
Fishdata <- read.csv(file = "Fish.csv")
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

## Build the best regression model you can that predicts the weight of perch
## Using only two predictor variables  

# Perch

```{r}
perch <- filter(Fishdata,Species == "Perch")
perch <- select(perch,-1)
``` 

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```


in this model, model perch, it appears that the best two plots to use to find the weight is Height and Width.



```{r}
which.max(summary.out$adjr2)
```


The best model of all of them is model 2.


```{r}
summary.out$which[2,]
```

The summary shows that the best two variables to use is Height and Width.

```{r}

```







